stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
    - data/raw/
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.remix
    - prepare.remix_split
    outs:
    - data/prepared
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - data/prepared/
    - src/preprocess.py
    params:
    - preprocess.seed
    - preprocess.normalize
    - preprocess.shuffle
    - preprocess.add_noise
    - preprocess.noise_amount
    - preprocess.noise_s_vs_p
    outs:
    - data/preprocessed/
  train:
    cmd: python3 src/train.py
    deps: 
    - src/train.py
    - src/model.py
    - data/prepared/
    params:
    - train.seed
    - train.validation_split
    - train.model
    - train.optimizer
    - train.loss
    - train.epochs
    - train.batch_size
    outs:
    - models/model.h5

  evaluate:
    cmd: python3 src/evaluate.py
    deps: 
    - src/evaluate.py
    - src/model.py
    - models/model.h5


