stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
    - data/raw/
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.remix
    - prepare.remix_split
    outs:
    - data/prepared
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - data/prepared/
    - src/preprocess.py
    params:
    - preprocess.seed
    - preprocess.normalize
    - preprocess.shuffle
    - preprocess.add_noise
    - preprocess.noise_amount
    - preprocess.noise_s_vs_p
    outs:
    - data/preprocessed/
  train:
    cmd: python3 src/train.py
    deps: 
    - src/train.py
    - src/models.py
    - data/preprocessed/
    params:
    - train.seed
    - train.validation_split
    - train.epochs
    - train.batch_size
    - model.name
    - model.optimizer
    - model.loss
    - model.mlp.units
    - model.mlp.activation
    - model.cnn.dense_units
    - model.cnn.conv_kernel_size
    - model.cnn.conv_units
    - model.cnn.dropout
    outs:
    - models/model.h5
    plots:
      - train.log.csv:
          cache: false

  evaluate:
    cmd: python3 src/evaluate.py
    deps: 
    - src/evaluate.py
    - models/model.h5
    metrics:
      - metrics.json:
          cache: false


