prepare:
  seed: 20210428
  remix: True
  remix_split: 0.20

preprocess:
  seed: 20210428
  normalize: True
  shuffle: False
  add_noise: False
  noise_amount: 0.0004
  noise_s_vs_p: 0.5

train:
  seed: 20210428
  validation_split: 0.2
  epochs: 10
  batch_size: 128

model:
  name: "mlp"
  optimizer: "Adam"
  loss: "CategoricalCrossentropy"
  mlp:
    units: 16
    activation: "relu"
  cnn:
    dense_units: 128
    activation: "relu"
    conv_kernel_size: 3
    conv_units: 32
    dropout: 0.5
  metrics:
    categorical_accuracy: True
    recall: True
    precision: True
    auc-roc: True
    auc-prc: True
    fp: True
    fn: True
    tp: True
    tn: False
